version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: partitures_postgres
    environment:
      POSTGRES_DB: partitures_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d partitures_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: